### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by Artanemis** [Artanemis/slax#3]
## User Auth

- [ ] MVP is completely styled and seeded
- [ ] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + R)
- [x] MVP handles errors with informative messages for use

### Features
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] Users can only sign in or sign up if not logged in

**Comment by david-dickinson** [comment]
- [ ] Fix button styling
- [ ] Handle errors on multiple lines
